
# 공통 설정
spring:
  application:
    name: defectapp
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 30MB
  webflux:
    multipart:
      max-in-memory-size: 256KB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: classpath:/static/,file:${defect.upload.path}

# 서버 기본 설정
server:
  servlet:
    session:
      timeout: 30m