# 공통 설정
spring:
  application:
    name: defectapp
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 30MB
  web:
    resources:
      static-locations: classpath:/static/,file:${defect.upload.path}

# JWT 설정
jwt:
  secret: bXlTZWNyZXRLZXlGb3JMb2NhbERldmVsb3BtZW50RW52aXJvbm1lbnQxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  expiration: 3600000   # 1시간 (밀리초)
  refresh-expiration: 259200000  # 3일 (밀리초)
  header: Authorization
  prefix: "Bearer "

---
# 로컬 개발 환경 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/defect?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: jmpark
    password: i/BpuFNAQD6KKzYT0W2OOh6WAxyC4GskqRdV4f0R6wsNIeWmiKT+G6JCkBWwGQ/7ZV0vW4lIOdEDi+po5o/CJNpMY27lfyPWBu5VHSbtDuJeFQ3l6uPsLEMOLsvKNPqLWvCshdkSNofUMwudsDwEMCLYqe7pHzTrhIHAvuSz910=
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

cookie:
  secure: false
  same-site: Lax
  domain: localhost

app:
  cors:
    allowed-origins: http://localhost:5173
    max-age: 3600
    allow-credentials: true

server:
  port: 8080

defect:
  upload:
    path: C:/Users/djd45/Desktop/defect-app-main/defect-app/uploads/defects

---
# 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

cookie:
  secure: true
  same-site: Strict

app:
  cors:
    allowed-origins: https://qms.jaemin.app
    max-age: 7200
    allow-credentials: true

server:
  port: 8080
  shutdown: graceful

defect:
  upload:
    path: ${UPLOAD_PATH}