# 공통 설정
spring:
  application:
    name: defectapp
  profiles:
    active: prod
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 30MB
  webflux:
    multipart:
      max-in-memory-size: 256KB
  web:
    resources:
      static-locations: classpath:/static/,file:${defect.upload.path}

# JWT 설정
jwt:
  secret: bXlTZWNyZXRLZXlGb3JMb2NhbERldmVsb3BtZW50RW52aXJvbm1lbnQxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  expiration: 3600000   # 1시간 (밀리초)
  refresh-expiration: 259200000  # 3일 (밀리초)
  header: Authorization
  prefix: "Bearer "
