# 로컬 개발 환경 설정
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/defect?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: jmpark
    password: i/BpuFNAQD6KKzYT0W2OOh6WAxyC4GskqRdV4f0R6wsNIeWmiKT+G6JCkBWwGQ/7ZV0vW4lIOdEDi+po5o/CJNpMY27lfyPWBu5VHSbtDuJeFQ3l6uPsLEMOLsvKNPqLWvCshdkSNofUMwudsDwEMCLYqe7pHzTrhIHAvuSz910=
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

# 서버 포트
server:
  port: 8080

# 결함 업로드 경로 설정
defect:
  upload:
    path: C:/Users/djd45/Desktop/defectapp/uploads/defects