import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { CU, DM, DP, MG, QA } from '@/constants/roles.constant.js'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'userManagement',
        path: '/user-management',
        title: '사용자 관리',
        translateKey: 'nav.singleMenuItem',
        icon: 'customers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MG],
        subMenu: [],
    },
    {
        key: 'userInfoUpdate',
        path: '/user-management/update/:userId',
        title: '사용자 정보',
        translateKey: 'nav.singleMenuItem.userManagement.userInfoUpdate',
        icon: 'customerDetails',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MG, CU, DM, DP, QA],
        subMenu: [],
    },
    {
        key: 'projectManagement',
        path: '/project-management',
        title: '프로젝트 관리',
        translateKey: 'nav.singleMenuItem.projectManagement',
        icon: 'projects',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MG, QA],
        subMenu: [],
    },
    {
        key: 'defectManagement',
        path: '/defect-management',
        title: '품질 관리',
        translateKey: 'nav.collapseMenu.defectManagement',
        icon: 'dashboardAnalytic',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [MG, CU, DM, DP, QA],
        subMenu: [
            {
                key: 'defectManagement.assigned',
                path: '/defect-management/assigned',
                title: '내게 할당된 결함',
                translateKey: 'nav.collapseMenu.defectManagement.assigned',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MG, CU, DM, DP, QA],
                subMenu: [],
            },
            {
                key: 'defectManagement.inProgress',
                path: '/defect-management/in-progress',
                title: '조치중 결함',
                translateKey: 'nav.collapseMenu.defectManagement.inProgress',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MG, CU, DM, DP, QA],
                subMenu: [],
            },
            {
                key: 'defectManagement.completed',
                path: '/defect-management/completed',
                title: '조치완료 결함',
                translateKey: 'nav.collapseMenu.defectManagement.completed',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MG, CU, DM, DP, QA],
                subMenu: [],
            },
            {
                key: 'defectManagement.todo',
                path: '/defect-management/todo',
                title: 'To-Do',
                translateKey: 'nav.collapseMenu.defectManagement.todo',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MG, CU, DM, DP, QA],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Collapse Menu',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'Collapse menu item 1',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
